# Generated by Django 4.1.7 on 2023-08-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='user',
        ),
    ]
